apiVersion: v1
kind: Pod
metadata:
  name: mongo-pod
  namespace: tarea-3
spec:
  containers:
  - name: mongo
    image: vcuellar/mongo
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc
