apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bienvenido a Nuestro Proyecto</title>
    <style>
        :root {
            --primary-color: #3498db;
            --secondary-color: #2c3e50;
            --background-color: #f4f4f4;
            --text-color: #333;
            --card-background: #fff;
        }
        body {
            font-family: 'Arial', sans-serif;
            line-height: 1.6;
            color: var(--text-color);
            margin: 0;
            padding: 0;
            background-color: var(--background-color);
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
            padding: 0 20px;
        }
        header {
            background: linear-gradient(to right, #3498db, #2980b9);
            color: white;
            text-align: center;
            padding: 2rem 0;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        h1 {
            margin: 0;
            font-size: 2.5rem;
            animation: fadeIn 1s ease-out;
        }
        @keyframes fadeIn {
            from { opacity: 0; }
            to { opacity: 1; }
        }
        h2 {
            color: var(--secondary-color);
            text-align: center;
            margin-top: 2rem;
        }
        .info-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 1.5rem;
            margin-top: 2rem;
        }
        .info-item {
            background: var(--card-background);
            padding: 1.5rem;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
            transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .info-item:hover {
            transform: translateY(-5px);
            box-shadow: 0 6px 12px rgba(0, 0, 0, 0.15);
        }
        .info-item h3 {
            color: var(--primary-color);
            margin-top: 0;
        }
        .info-item ul {
            list-style-type: none;
            padding-left: 0;
        }
        .info-item ul li {
            margin-bottom: 0.5rem;
            padding-left: 1.5rem;
            position: relative;
        }
        .info-item ul li::before {
            content: "✔";
            color: var(--primary-color);
            position: absolute;
            left: 0;
        }
        .section {
            background: var(--card-background);
            padding: 2rem;
            margin: 2rem 0;
            border-radius: 10px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        }
        .step {
            display: flex;
            flex-wrap: wrap;
            align-items: center;
            justify-content: center;
            margin: 1.5rem 0;
        }
        .step img {
            width: 80px;
            height: auto;
            margin: 10px;
        }
        .arrow {
            font-size: 1.5rem;
            margin: 0 10px;
            color: var(--primary-color);
        }
        footer {
            background-color: var(--secondary-color);
            color: white;
            text-align: center;
            padding: 1rem 0;
            margin-top: 2rem;
        }
        .github-link {
            display: inline-flex;
            align-items: center;
            margin-top: 1rem;
            padding: 0.75rem 1.5rem;
            background-color: #24292e;
            color: white;
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s ease, transform 0.3s ease;
            font-weight: bold;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }
        .github-link:hover {
            background-color: #2c3e50;
            transform: translateY(-2px);
        }
        .github-icon {
            margin-right: 10px;
            font-size: 1.5rem;
        }
        @media (max-width: 768px) {
            .info-grid {
                grid-template-columns: 1fr;
            }
            .step {
                flex-direction: column;
            }
            .arrow {
                transform: rotate(90deg);
                margin: 10px 0;
            }
        }
    </style>
    </head>
    <body>
    <header>
        <div class="container">
            <h1>Bienvenidos</h1>
        </div>
    </header>

    <main class="container">
        <h2>Información del Proyecto</h2>

        <div class="info-grid">
            <div class="info-item">
                <h3>Alojamiento</h3>
                <p>Esta página está alojada en un cluster de Kubernetes (EKS) en Amazon Web Services (AWS).</p>
            </div>

            <div class="info-item">
                <h3>Servidor Web</h3>
                <p>Estamos utilizando Nginx como servidor web para servir esta página.</p>
            </div>

        </div>

        <h2>Esquema del Proyecto IaC</h2>

        <div class="section">
            <div class="step">
                <div class="arrow">➡️</div>
                <img src="https://d1.awsstatic.com/logos/cloudformation/logo-cloudformation.png" alt="CloudFormation" width="100">
                <div class="arrow">➡️</div>
                <img src="https://logos-world.net/wp-content/uploads/2020/11/Amazon-Web-Services-AWS-Logo.png" alt="AWS EC2" width="100">
            </div>

            <div class="step">
                <div class="arrow">⬇️</div>
            </div>

            <div class="step">
                <img src="https://cdn.worldvectorlogo.com/logos/aws-cli.svg" alt="AWS CLI">
                <div class="arrow">➡️</div>
                <img src="https://cdn.worldvectorlogo.com/logos/kubernetes-2.svg" alt="kubectl">
                <div class="arrow">➡️</div>
                <img src="https://d33wubrfki0l68.cloudfront.net/c498c40d0e8f96b60f16224695f55f42e69a2265/17c38/images/logo-eks.svg" alt="EKS" width="100">
            </div>

            <div class="step">
                <div class="arrow">⬇️</div>
            </div>

            <div class="step">
                <img src="https://cdn.worldvectorlogo.com/logos/nginx-1.svg" alt="Nginx" width="80">
                <div class="arrow">➡️</div>
                <img src="https://www.docker.com/wp-content/uploads/2022/03/vertical-logo-monochromatic.png" alt="Docker" width="80">
                <div class="arrow">➡️</div>
                <img src="https://helm.sh/img/helm.svg" alt="Helm" width="80">
            </div>

            <div class="step">
                <div class="arrow">⬇️</div>
            </div>
        </div>
    </main>

    <footer>
        <div class="container">
            <p>&copy; 2024 Nuestro Proyecto. Todos los derechos reservados.</p>
        </div>
    </footer>
    </body>
    </html>